# Generated by Django 5.0.2 on 2024-03-01 07:33

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('student', 'Student')], max_length=10, null=True),
        ),
    ]
