# Generated by Django 5.0.2 on 2024-03-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_alter_myuser_country_alter_myuser_employment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
    ]
