# Generated by Django 5.0.2 on 2024-03-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0001_initial'),
        ('ProfileApp', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PostsApp.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
